<#-- @formatter:off -->
<#--import at.gridtec.lambda4j.core.*;-->
import at.gridtec.lambda4j.core.exception.*;
import at.gridtec.lambda4j.core.util.*;
import at.gridtec.lambda4j.functions.*;
<#--import at.gridtec.lambda4j.comparator.*;-->
import at.gridtec.lambda4j.functions.consumer.*;
import at.gridtec.lambda4j.functions.consumer.bi.*;
import at.gridtec.lambda4j.functions.consumer.bi.obj.*;
import at.gridtec.lambda4j.functions.consumer.tri.*;
import at.gridtec.lambda4j.functions.consumer.tri.obj.*;
import at.gridtec.lambda4j.functions.function.*;
import at.gridtec.lambda4j.functions.function.bi.*;
import at.gridtec.lambda4j.functions.function.bi.conversion.*;
import at.gridtec.lambda4j.functions.function.bi.obj.*;
import at.gridtec.lambda4j.functions.function.bi.to.*;
import at.gridtec.lambda4j.functions.function.conversion.*;
import at.gridtec.lambda4j.functions.function.to.*;
import at.gridtec.lambda4j.functions.function.tri.*;
import at.gridtec.lambda4j.functions.function.tri.conversion.*;
import at.gridtec.lambda4j.functions.function.tri.obj.*;
import at.gridtec.lambda4j.functions.function.tri.to.*;
import at.gridtec.lambda4j.functions.operator.*;
import at.gridtec.lambda4j.functions.operator.unary.*;
import at.gridtec.lambda4j.functions.operator.binary.*;
import at.gridtec.lambda4j.functions.operator.ternary.*;
import at.gridtec.lambda4j.functions.predicate.*;
import at.gridtec.lambda4j.functions.predicate.bi.*;
import at.gridtec.lambda4j.functions.predicate.bi.obj.*;
import at.gridtec.lambda4j.functions.predicate.tri.*;
import at.gridtec.lambda4j.functions.predicate.tri.obj.*;
import at.gridtec.lambda4j.functions.runnable.*;
import at.gridtec.lambda4j.functions.supplier.*;
import org.apache.commons.lang3.tuple.*;
import javax.annotation.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.*;
<#-- @formatter:on -->
